import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Attendance",
  description: "Generated by Ansh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <div style={{ backgroundColor: "#EAF1FF" }}>
          <div className="md:max-w-6xl lg:max-w-6xl mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
